model:
  # Optimizer
  lr: 0.001
  weight_decay: 0.0001
  # Scheduler
  milestones: [10]
  gamma: 0.5
  # Model
  d_model: 128
  dim_feedforward: 256
  nhead: 4
  dropout: 0.3
  num_decoder_layers: 3
  max_output_len: 150
  vocab_path: '/usr/hsc_project/latexOCR/image-to-latex/data/vocab.json'